#!/usr/bin/env python3
"""
Unit test for scripts/bash/run_with_flash.sh

This is intended to be runnable in CI, e.g.:

    QEMU_RISCV32_BIN=/path/to/qemu-system-riscv32 \
    python3 -m tests.unit.test_run_with_flash

Requirements:
    - QEMU built with the neorv32 machine
    - qemu_neorv32_extras repo layout as expected
    - flash_hello_world_64mb.bin already generated by generate_flash_image.sh
"""

import os
import sys
import time
import subprocess
from pathlib import Path

OVERALL_TIMEOUT_SEC = 90.0  # a bit more time, since we also boot Hello World


def find_repo_root() -> Path:
    """Return repo root as Path, based on this file location."""
    this_file = Path(__file__).resolve()
    repo_root = this_file.parents[2]  # tests/unit/ -> tests/ -> repo root
    if not (repo_root / "README.md").is_file():
        raise RuntimeError(f"Could not find README.md at {repo_root}")
    return repo_root


def get_qemu_bin() -> Path:
    """Get QEMU binary path from env var QEMU_RISCV32_BIN."""
    env_name = "QEMU_RISCV32_BIN"
    qemu_path = os.environ.get(env_name)
    if not qemu_path:
        raise RuntimeError(
            f"Environment variable {env_name} is not set.\n"
            f"Set it to your qemu-system-riscv32 binary, e.g.:\n"
            f"    export {env_name}=/path/to/qemu-system-riscv32"
        )
    qemu_bin = Path(qemu_path).expanduser().resolve()
    if not qemu_bin.is_file():
        raise RuntimeError(f"QEMU binary not found at {qemu_bin}")
    return qemu_bin


def ensure_flash_image_exists(repo_root: Path) -> None:
    """
    Make sure the default flash image exists.

    If you want, you can later auto-run generate_flash_image.sh from here,
    but for now we just assert it's present so CI can call the generator first.
    """
    flash_img = repo_root / "binaries" / "flash_images" / "flash_uboot_64mb.bin"
    if not flash_img.is_file():
        raise RuntimeError(
            f"Flash image not found at {flash_img}\n"
            f"Run scripts/bash/generate_flash_image.sh first."
        )


def run_with_flash_test() -> None:
    repo_root = find_repo_root()
    qemu_bin = get_qemu_bin()
    ensure_flash_image_exists(repo_root)

    run_script = repo_root / "scripts" / "bash" / "run_with_flash.sh"
    if not run_script.is_file():
        raise RuntimeError(f"run_with_flash.sh not found at {run_script}")
    if not os.access(run_script, os.X_OK):
        raise RuntimeError(f"run_with_flash.sh is not executable: {run_script}")

    cmd = [str(run_script), "-q", str(qemu_bin)]

    print(f"[INFO] Repo root:  {repo_root}")
    print(f"[INFO] QEMU bin:   {qemu_bin}")
    print(f"[INFO] Script:     {run_script}")
    print(f"[INFO] Command:    {' '.join(cmd)}")
    sys.stdout.flush()

    start_time = time.time()

    proc = subprocess.Popen(
        cmd,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    bootloader_seen = False
    hello_seen = False

    try:
        while True:
            elapsed = time.time() - start_time
            if elapsed > OVERALL_TIMEOUT_SEC:
                print(
                    f"[ERROR] Timeout: QEMU did not complete within "
                    f"{OVERALL_TIMEOUT_SEC} seconds"
                )
                proc.terminate()
                try:
                    proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    proc.kill()
                raise RuntimeError(
                    "Timeout waiting for QEMU / bootloader + Hello World output"
                )

            line = proc.stdout.readline()
            if line == "":
                # EOF
                break

            # Echo QEMU output to our stdout (useful for CI logs)
            sys.stdout.write(line)
            sys.stdout.flush()

            if "NEORV32 Bootloader" in line:
                bootloader_seen = True

            if "Hello world!" in line or "Hello world! :)" in line:
                hello_seen = True
                print("[INFO] Detected Hello World payload, sending Ctrl-a x...")
                sys.stdout.flush()

                if proc.stdin and proc.poll() is None:
                    # Ctrl-a, then 'x' to ask QEMU to exit
                    proc.stdin.write("\x01x")
                    proc.stdin.flush()
                # We now expect QEMU to terminate soon; we'll exit on EOF/exit code.

        # After stdout loop, wait for process to really exit
        try:
            rc = proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            print("[ERROR] QEMU did not exit after Ctrl-a x; killing it.")
            proc.kill()
            rc = proc.wait(timeout=5)

        if not bootloader_seen:
            raise RuntimeError(
                "Did not detect 'NEORV32 Bootloader' in QEMU output; boot may have failed."
            )

        if not hello_seen:
            raise RuntimeError(
                "Did not detect 'Hello world!' in QEMU output; "
                "flash image or auto-boot may not be working."
            )

        if rc != 0:
            raise RuntimeError(f"QEMU exited with non-zero status: {rc}")

        print("[INFO] run_with_flash.sh test PASSED.")

    finally:
        # Safety: ensure process is not left running
        if proc.poll() is None:
            try:
                proc.terminate()
                proc.wait(timeout=5)
            except Exception:
                try:
                    proc.kill()
                except Exception:
                    pass


def main() -> int:
    try:
        run_with_flash_test()
    except Exception as e:
        print(f"[FAIL] {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())

